### ISSUE TITLE
Lots of error occuring while installing dependencies

### ISSUE THREAD

**Issue by vaasu2002** [BrianHHough/inspirational-quote-generator-freeCodeCamp#1]
**npm WARN** deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
**npm ERR!** code ERR_SOCKET_TIMEOUT
**npm ERR!** network Socket timeout
**npm ERR!** network This is a problem related to network connectivity.
**npm ERR!** network In most cases you are behind a proxy or have bad network settings.
**npm ERR!** network 
**npm ERR!** network If you are behind a proxy, please make sure that the
**npm ERR!** network 'proxy' config is set properly.  See: 'npm help config'

**Comment by BrianHHough** [comment]
Hey @vaasu2002 — what is your OS and which version of `npm` do you have installed?

**Comment by vaasu2002** [comment]
@BrianHHough 
npm version - 8.19.2
os - windows 11

**Comment by BrianHHough** [comment]
@vaasu2002 interesting — sorry you're running into issues. In the log, it does seem like there is an issue around network connectivity. The `ERR_SOCKET_TIMEOUT` error seems as though the npm client can't establish or maintain a connection to the npm registry long enough to install everything.

My suspicion is that the timeout of npm's configuration is set to stop if it's running for too long.

Here are a couple debugs you could try that I've used in other projects if I ever ran into something like this:

1. Check your internet connectivity: make sure you have a stable wifi connection. Also if you're on a VPN, you might need to jump off the VPN while installing in case this is preventing the stable connection to npm.
2. Try installing the packages one-by-one. So you could start with a blank `next.js / typescript` project and instead of installing the whole list of additional dependencies, you would install them one by one to avoid a timeout.
3. Try updating npm with `npm install -g npm@latest` to make sure you are using the latest and greatest of `npm`.
4. Delete the `node_modules` folder and try to `npm i` from the root again.

**Comment by vaasu2002** [comment]
@BrianHHough thank you was able to remove all the error, warning are still there but now it running, Thank you!

**Comment by vaasu2002** [comment]
@BrianHHough thank you were able to remove all the errors, Warnings are still there but now it running, Thank you!

**Comment by BrianHHough** [comment]
Amazing!! Great work @vaasu2002!! 🙏👏 Happy building!
